---



- name: start up mysql container
  docker_container:
    name: "{{ mysql_container }}"
    image: "{{ mysql_image }}"
    state: started
    volumes:
      - "{{ mysql_data_dir }}:/var/lib/mysql"
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
      MYSQL_DATABASE: "{{ sonar_datanase_name }}"
      MYSQL_USER: "{{ sonar_mysql_user }}"
      MYSQL_PASSWORD: "{{ sonar_mysql_password }}"
    ports:
      - "3306:3306"



- name: Ensure Sonar container has an up-to-date configuration
  docker_container:
    name: "{{ sonar_container_name }}"
    image: "{{ sonar_image }}"
    state: started
    restart: yes
    links:
      - "{{ mysql_container }}:mysql"
    ports:
      - "{{ sonar_port }}:9000"
      - "{{ sonar_port_2 }}:9092"
    volumes:
      - "{{ sonar_data_path }}:/opt/sonarqube/data"
      - "{{ sonar_conf_path }}:/opt/sonarqube/conf"
      - "{{ sonar_extensions_path }}:/opt/sonarqube/extensions"
      - "{{ sonar_logs_path }}:/opt/sonarqube/logs"
    command: "{{ sonar_command_var }}"
    env:
      SONARQUBE_JDBC_URL: "{{ sonar_jdbc_url }}"
      SONARQUBE_JDBC_USERNAME: "{{ sonar_mysql_user }}"
      SONARQUBE_JDBC_PASSWORD: "{{ sonar_mysql_password }}"
  tags:
    - docker


- name: Make sure Sonar is responding on the configured port.
  wait_for: port={{ sonar_port }} delay=3 timeout=300

